# Generated by Django 4.2.6 on 2023-11-18 18:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0002_alter_articles_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=models.SET('Owner was deleted'), to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
